server:
  port: 10010
spring:
  application:
    name: itcast-zuul
zuul:
  routes:
#    service-provider: /service-provider/**
    service-provider: /service-provider/**
    serviceId: service-provider
#    service-consumer: /consumer/**
#  prefix: /api


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka

#ribbon:
#  ReadTimeout: 60000
#  ConnectTimeout: 60000
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 60000




