server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: hwy

mybatis:
  type-aliases-package: cn.itcast.service.pojo

