eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
mybatis:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: cn.itcast.service.pojo
server:
  port: 8083
spring:
  application:
    name: service-provider
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: imooc_mall_datasource
    password: hwy
    url: jdbc:mysql://127.0.0.1:3306/leyou?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
